# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Kafka exporter configuration for traces
exporters:
  kafka:
    brokers:
      - kafka:9092  # Uses the existing Kafka service in docker-compose
    protocol_version: 2.1.0
    client_id: "otel-collector-traces"
    traces:
      topic: "otlp-traces"
      encoding: otlp_json  # Preserves all OpenTelemetry trace data
    partition_traces_by_id: true  # Distributes traces by trace ID
    timeout: 10s
    metadata:
      full: true
      
service:
  pipelines:
    traces:
      exporters: [otlp, debug, spanmetrics, kafka]  # MUST include spanmetrics!
